development:
  adapter: mysql2
  database: expert_development
  username: root
  password: 
  encoding: utf8

test:
  adapter: mysql2
  database: expert_test
  username: root
  password: 
  encoding: utf8
  host: localhost
